version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - api_db
    command: bash -c "cd app/settings/ && sleep 15 && python run_db_migration.py database_init.sql && python run_db_seed.py && cd ../../ && python run.py"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - ${POSTGRES_PORT}:5432
    networks:
      - api_db

networks:
  api_db:
    driver: bridge